### ISSUE TITLE
Replace xls with csv for retrieving students' details

### ISSUE THREAD

**Issue by AntonisGkortzis** [AntonisGkortzis/ExamQuestionnaireScanner#14]
https://github.com/AntonisGkortzis/ExamQuestionnaireScanner/blob/afcb26762a25cd51fbfc05730f9ea6f3ed7dfbb5/CSVparser.py#L54
Instead of reading the xls file for retrieving the students' details, read a single-column csv file like the following:
``` 
AM
1273651
0221312
4312334
1233434 
```
We should replace any xls read/write..

**Comment by stefanos1316** [comment]
Changed it!
